apiVersion: v1
kind: Service
metadata:
  name: prod-yarn-resourcemanager
  namespace: sigs
spec:
  ports:
  - port: 8032
    name: web-ui
  - port: 8030
    name: scheduler
  - port: 8088
    name: web-app
  - port: 8090
    name: web-app-https
  - port: 8031
    name: tracker
  - port: 8033
    name: admin-ui
  - port: 19888 
    name: history-ui
  - port: 10020 
    name: history-address
  clusterIP: None
  selector:
     app: yarn
     component: resourcemanager
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prod-yarn-resourcemanager
  namespace: sigs
  labels:
    app: yarn
    component: resourcemanager
spec:
  serviceName: prod-yarn-resourcemanager
  replicas: 1 
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  selector:
     matchLabels:
        app: yarn
        component: resourcemanager
  template:
    metadata:
      labels:
        app: yarn
        component: resourcemanager
    spec:
      containers:
        - name: prod-yarn-resourcemanager
          imagePullPolicy: 'Always'
          image: applysq/yarn:1.0.0_resource_hadoop_3.2.1
          resources:
            requests:
              cpu: 400m
              memory: 400m
          ports:
            - containerPort: 8032
              name: web-ui
              protocol: TCP  
            - containerPort: 8030
              name: scheduler
              protocol: TCP  
            - containerPort: 8088
              name: web-app
              protocol: TCP 
            - containerPort: 8090
              name: web-app-https
              protocol: TCP  
            - containerPort: 8031
              name: tracker
              protocol: TCP  
            - containerPort: 8033
              name: admin-ui
              protocol: TCP   
            - containerPort: 19888 
              name: history-ui
              protocol: TCP   
            - containerPort: 10020 
              name: history-address
              protocol: TCP   
          args: ["yarn", "resourcemanager"]
          envFrom:
             - configMapRef:
                  name: yarn-config-resource
      volumes:
        - name: config
          configMap:
            name: yarn-config-resource
        - name: data
          emptyDir: {}
